In [1]:
import pandas as pd

In [ ]:
new_dict={
    "anime":["Pokemon","Solo leveling","Dragon Ball"],
    "Days":[1,2,3],
    "sqrt":[1.1,2.2,3.3]
}
new_dict

In [5]:
pd.DataFrame(new_dict)

           anime  Days  sqrt
0        Pokemon     1   1.1
1  Solo leveling     2   2.2
2    Dragon Ball     3   3.3

In [9]:
pd.Series([1,2,3,4,5])

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [10]:
pd.Series([1,2,3,4,5],
         index=["One","Two","Three","Four","five"],
         name="Numbers")

One      1
Two      2
Three    3
Four     4
five     5
Name: Numbers, dtype: int64

In [2]:
pd.DataFrame(
    [["Pokemon",1,1.2],["Dragon ball",2,1.2]],
    columns=["Anime","Index","Sqrt"]
)

         Anime  Index  Sqrt
0      Pokemon      1   1.2
1  Dragon ball      2   1.2

In [5]:
pd.Series(["Pokemon","SAO"],name="Anime")

0    Pokemon
1        SAO
Name: Anime, dtype: object

In [6]:
pd.Series(
    [["Pokemon",1,1.2],["Dragon ball",2,1.2]],
    name=["Anime","Index","Sqrt"]
)

TypeError: Series.name must be a hashable type

In [2]:
customers={
    "cust_id":[101,101,101,102,102,102,102,103]
}
cust=pd.DataFrame(customers)
cust

   cust_id
0      101
1      101
2      101
3      102
4      102
5      102
6      102
7      103

In [5]:
cust.value_counts()

cust_id
102        4
101        3
103        1
Name: count, dtype: int64

In [9]:
print(cust.nunique().sum())

3